[package]
name = "asteroides_sdl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kira = "0.7.1"
once_cell = "1.17.0"
rand = "0.8.5"
sdl2 = "0.35.2"
specs = "0.18.0"
specs-derive = "0.4.1"